using System.Collections.Immutable;
using System.Linq;
using System.Text;
using SqlPartial.Generator.Models;

namespace SqlPartial.Generator.Core
{
    internal static class SourceBuilder
    {
        // ── SqlStrings struct ────────────────────────────────────────────────

        /// <summary>
        /// Generates the ISqlString interface and the SqlStrings/SqlDynamic structs.
        /// Called once per project when ExternalSqlStringsType is not set.
        /// </summary>
        public static string BuildSqlStringsStruct(GeneratorConfig config, bool supportsNullable)
        {
            var sb = new StringBuilder();
            var ns = config.SqlStringsNamespace;
            var nullable = supportsNullable && config.NullableEnabled ? "enable" : "disable";
            var stringType = supportsNullable ? "string?" : "string";
            var funcType = supportsNullable ? "System.Func<string>?" : "System.Func<string>";

            sb.AppendLine("// <auto-generated/>");
            if (supportsNullable)
            {
                sb.AppendLine($"#nullable {nullable}");
            }

            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            // ── ISqlString Interface ─────────────────────────────────────────
            sb.AppendLine("    /// <summary>Common interface for both static and dynamic SQL strings.</summary>");
            sb.AppendLine("    public interface ISqlString");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>ANSI SQL — shared fallback.</summary>");
            sb.AppendLine("        string AnsiSql { get; }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Returns the SQL for a given provider, falling back to AnsiSql.</summary>");
            sb.AppendLine("        string Get(string providerName);");
            sb.AppendLine("    }");
            sb.AppendLine();

            // ── SqlStrings Struct (Static) ───────────────────────────────────
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Holds static SQL query strings. Supports implicit conversion from string.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public readonly struct SqlStrings : ISqlString");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>ANSI SQL — shared fallback for all providers.</summary>");
            sb.AppendLine("        public string AnsiSql { get; }");
            sb.AppendLine();

            foreach (var providerName in config.DistinctProviderNames)
            {
                var fieldName = "_" + providerName.ToLowerInvariant();
                sb.AppendLine($"        private readonly {stringType} {fieldName};");
                sb.AppendLine($"        /// <summary>{providerName} specific SQL. Falls back to <see cref=\"AnsiSql\"/> when null.</summary>");
                sb.AppendLine($"        public string {providerName} => {fieldName} ?? AnsiSql;");
                sb.AppendLine();
            }

            // Full Constructor
            var providerNames = config.DistinctProviderNames.ToArray();
            sb.Append("        public SqlStrings(string ansiSql");
            foreach (var providerName in providerNames)
            {
                sb.Append($", {stringType} {providerName.ToLowerInvariant()} = null");
            }
            sb.AppendLine(")");
            sb.AppendLine("        {");
            sb.AppendLine("            AnsiSql = ansiSql;");
            foreach (var providerName in providerNames)
            {
                sb.AppendLine($"            _{providerName.ToLowerInvariant()} = {providerName.ToLowerInvariant()};");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // Manual Constructor (ANSI only) - Only if there are providers (to avoid CS0111)
            if (providerNames.Length > 0)
            {
                sb.Append("        public SqlStrings(string ansiSql) : this(ansiSql");
                foreach (var _ in providerNames) sb.Append(", null");
                sb.AppendLine(") { }");
                sb.AppendLine();
            }

            // Implicit operators
            sb.AppendLine("        /// <summary>Implicit conversion from string creates an ANSI-only SqlStrings.</summary>");
            sb.AppendLine("        public static implicit operator SqlStrings(string ansiSql) => new SqlStrings(ansiSql);");
            sb.AppendLine("        /// <summary>Implicit conversion to string returns <see cref=\"AnsiSql\"/>.</summary>");
            sb.AppendLine("        public static implicit operator string(SqlStrings s) => s.AnsiSql;");
            sb.AppendLine();

            // Get method
            sb.AppendLine("        public string Get(string providerName)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (providerName)");
            sb.AppendLine("            {");
            foreach (var providerName in config.DistinctProviderNames)
            {
                sb.AppendLine($"                case \"{providerName}\": return {providerName};");
            }
            sb.AppendLine("                default: return AnsiSql;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // ── SqlDynamic Struct (Factory-based) ────────────────────────────
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Holds dynamic SQL factories. Use for ad-hoc SQL that needs per-DBMS logic.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public readonly struct SqlDynamic : ISqlString");
            sb.AppendLine("    {");
            sb.AppendLine($"        private readonly {funcType} _ansi;");
            sb.AppendLine("        /// <summary>ANSI SQL — shared fallback. Evaluated via factory.</summary>");
            sb.AppendLine("        public string AnsiSql => _ansi?.Invoke() ?? string.Empty;");
            sb.AppendLine();

            foreach (var providerName in config.DistinctProviderNames)
            {
                var fieldName = "_" + providerName.ToLowerInvariant() + "Factory";
                sb.AppendLine($"        private readonly {funcType} {fieldName};");
                sb.AppendLine($"        /// <summary>{providerName} specific SQL. Evalulated via factory, falls back to <see cref=\"AnsiSql\"/>.</summary>");
                sb.AppendLine($"        public string {providerName} => {fieldName}?.Invoke() ?? AnsiSql;");
                sb.AppendLine();
            }

            // Constructor for factories
            sb.Append("        public SqlDynamic(");
            bool first = true;
            foreach (var providerName in config.DistinctProviderNames)
            {
                if (!first) sb.Append(", ");
                sb.Append($"{funcType} {providerName.ToLowerInvariant()} = null");
                first = false;
            }
            if (!first) sb.Append(", ");
            sb.AppendLine($"{funcType} ansi = null)");
            sb.AppendLine("        {");
            sb.AppendLine("            _ansi = ansi;");
            foreach (var providerName in config.DistinctProviderNames)
            {
                sb.AppendLine($"            _{providerName.ToLowerInvariant()}Factory = {providerName.ToLowerInvariant()};");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // Constructor for pure ANSI string (wraps in factory)
            sb.Append("        public SqlDynamic(string ansiSql) : this(");
            for (int i = 0; i < providerNames.Length; i++) sb.Append("null, ");
            sb.AppendLine("() => ansiSql) { }");
            sb.AppendLine();

            // Get method
            sb.AppendLine("        public string Get(string providerName)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (providerName)");
            sb.AppendLine("            {");
            foreach (var providerName in config.DistinctProviderNames)
            {
                sb.AppendLine($"                case \"{providerName}\": return {providerName};");
            }
            sb.AppendLine("                default: return AnsiSql;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        // ── Partial class ────────────────────────────────────────────────────

        /// <summary>
        /// Generates one partial class file containing all SqlStrings properties
        /// for a single ClassName within a namespace.
        /// </summary>
        public static string BuildPartialClass(
            string ns,
            string className,
            ImmutableArray<SqlQueryGroup> groups,
            GeneratorConfig config,
            bool supportsNullable)
        {
            // Resolve the SqlStrings type name to use
            var stringsType = config.ExternalSqlStringsType ?? $"{config.SqlStringsNamespace}.SqlStrings";

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            if (supportsNullable)
            {
                sb.AppendLine(config.NullableEnabled ? "#nullable enable" : "#nullable disable");
            }

            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    partial class {className}");
            sb.AppendLine("    {");

            foreach (var group in groups)
            {
                var ansiContent = group.GetContent(FilePathParser.AnsiSqlProviderName);
                sb.AppendLine($"        private static readonly {stringsType} Sql{group.QueryName} = new {stringsType}(");
                sb.Append($"            @\"{ansiContent}\"");

                // Provider-specific — only emit when the file exists for that provider name
                foreach (var providerName in config.DistinctProviderNames)
                {
                    if (group.ContentByProviderName.TryGetValue(providerName, out var content))
                    {
                        sb.AppendLine(",");
                        sb.Append($"            {providerName.ToLowerInvariant()}: @\"{content}\"");
                    }
                }

                sb.AppendLine(");");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
