using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using SqlPartial.Generator.Models;

namespace SqlPartial.Generator.Core;

internal static class SourceBuilder
{
    // ── SqlAttribute ─────────────────────────────────────────────────────

    public static string BuildSqlAttribute()
    {
        return @"// <auto-generated/>
#if !SQLPARTIAL_USE_SHARED_NAMESPACE
namespace SqlPartial.Abstractions
{
    /// <summary>
    /// Marks a parameter to be replaced with provider-specific SQL string overloads.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Parameter)]
    public sealed class SqlAttribute : System.Attribute { }
}
#endif
";
    }

    // ── SqlStrings struct ────────────────────────────────────────────────

    /// <summary>
    /// Generates the ISqlString interface and the SqlStrings/SqlDynamic structs.
    /// Called once per project when ExternalSqlStringsType is not set.
    /// </summary>
    public static string BuildSqlStringsStruct(GeneratorConfig config, bool supportsNullable)
    {
        // If we are using shared types from another project, don't emit them here.
        if (config.UseSharedNamespace != null)
        {
            return "// Shared types are imported from " + config.UseSharedNamespace;
        }

        var sb = new StringBuilder();
        var ns = config.EmitSharedNamespace ?? config.SqlStringsNamespace;
        var visibility = config.EmitSharedNamespace != null ? "public" : "internal";
        var nullable = supportsNullable && config.NullableEnabled ? "enable" : "disable";
        var stringType = supportsNullable ? "string?" : "string";
        var funcType = supportsNullable ? "System.Func<string>?" : "System.Func<string>";

        sb.AppendLine("// <auto-generated/>");
        if (supportsNullable)
        {
            sb.AppendLine($"#nullable {nullable}");
        }

        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");

        // ── ISqlString Interface ─────────────────────────────────────────
        sb.AppendLine("    /// <summary>Common interface for both static and dynamic SQL strings.</summary>");
        sb.AppendLine($"    {visibility} interface ISqlString");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Default SQL — shared default.</summary>");
        sb.AppendLine("        string Default { get; }");
        sb.AppendLine();

        foreach (var providerName in config.DistinctProviderNames)
        {
            sb.AppendLine($"        /// <summary>{providerName} specific SQL.</summary>");
            sb.AppendLine($"        string {providerName} {{ get; }}");
            sb.AppendLine();
        }

        sb.AppendLine("        /// <summary>Returns the SQL for a given provider, falling back to Default.</summary>");
        sb.AppendLine("        string Get(string providerName);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ── SqlStrings Struct (Static) ───────────────────────────────────
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Holds static SQL query strings.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    {visibility} readonly struct SqlStrings : ISqlString");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly {stringType} _default;");
        sb.AppendLine("        /// <summary>Default SQL — shared default for all providers.</summary>");
        sb.AppendLine("        public string Default => _default ?? string.Empty;");
        sb.AppendLine();

        foreach (var providerName in config.DistinctProviderNames)
        {
            var fieldName = "_" + providerName.ToLowerInvariant();
            sb.AppendLine($"        private readonly {stringType} {fieldName};");
            sb.AppendLine($"        /// <summary>{providerName} specific SQL. Falls back to <see cref=\"Default\"/> when null.</summary>");
            sb.AppendLine($"        public string {providerName} => {fieldName} ?? Default;");
            sb.AppendLine();
        }

        // Full Constructor
        var providerNames = config.DistinctProviderNames.ToArray();
        sb.Append("        public SqlStrings(");
        bool first = true;

        foreach (var providerName in providerNames)
        {
            if (!first) sb.Append(", ");
            sb.Append($"{stringType} {providerName.ToLowerInvariant()} = null");
            first = false;
        }

        if (!first) sb.Append(", ");
        sb.AppendLine($"{stringType} @default = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            _default = @default;");

        foreach (var providerName in providerNames)
        {
            sb.AppendLine($"            _{providerName.ToLowerInvariant()} = {providerName.ToLowerInvariant()};");
        }

        sb.AppendLine("        }");
        sb.AppendLine();

        // Manual Constructor (Default only) - Only if there are providers (to avoid CS0111)
        if (providerNames.Length > 0)
        {
            sb.Append("        public SqlStrings(string @default) : this(");
            for (int i = 0; i < providerNames.Length; i++) sb.Append("null, ");
            sb.AppendLine("@default) { }");
            sb.AppendLine();
        }

        // Get method
        sb.AppendLine("        public string Get(string providerName)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (providerName)");
        sb.AppendLine("            {");
        foreach (var providerName in config.DistinctProviderNames)
        {
            sb.AppendLine($"                case \"{providerName}\": return {providerName};");
        }
        sb.AppendLine("                default: return Default;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ── SqlDynamic Struct (Factory-based) ────────────────────────────
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Holds dynamic SQL factories. Use for ad-hoc SQL that needs per-DBMS logic.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    {visibility} readonly struct SqlDynamic : ISqlString");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly {funcType} _default;");
        sb.AppendLine("        /// <summary>Default SQL — shared default. Evaluated via factory.</summary>");
        sb.AppendLine("        public string Default => _default?.Invoke() ?? string.Empty;");
        sb.AppendLine();

        foreach (var providerName in config.DistinctProviderNames)
        {
            var fieldName = "_" + providerName.ToLowerInvariant() + "Factory";
            sb.AppendLine($"        private readonly {funcType} {fieldName};");
            sb.AppendLine($"        /// <summary>{providerName} specific SQL. Evalulated via factory, falls back to <see cref=\"Default\"/>.</summary>");
            sb.AppendLine($"        public string {providerName} => {fieldName}?.Invoke() ?? Default;");
            sb.AppendLine();
        }

        // Constructor for factories
        sb.Append("        public SqlDynamic(");
        bool dynamicFirst = true;

        foreach (var providerName in config.DistinctProviderNames)
        {
            if (!dynamicFirst) sb.Append(", ");
            sb.Append($"{funcType} {providerName.ToLowerInvariant()} = null");
            dynamicFirst = false;
        }

        if (!dynamicFirst) sb.Append(", ");
        sb.AppendLine($"{funcType} @default = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            _default = @default;");

        foreach (var providerName in config.DistinctProviderNames)
        {
            sb.AppendLine($"            _{providerName.ToLowerInvariant()}Factory = {providerName.ToLowerInvariant()};");
        }

        sb.AppendLine("        }");
        sb.AppendLine();

        // Constructor for pure Default string (wraps in factory)
        sb.Append("        public SqlDynamic(string @default) : this(");
        for (int i = 0; i < providerNames.Length; i++) sb.Append("null, ");
        sb.AppendLine("() => @default) { }");
        sb.AppendLine();

        // Get method
        sb.AppendLine("        public string Get(string providerName)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (providerName)");
        sb.AppendLine("            {");

        foreach (var providerName in config.DistinctProviderNames)
        {
            sb.AppendLine($"                case \"{providerName}\": return {providerName};");
        }

        sb.AppendLine("                default: return Default;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("}");

        return sb.ToString();
    }

    // ── Partial class ────────────────────────────────────────────────────

    /// <summary>
    /// Generates one partial class file containing all SqlStrings properties
    /// for a single ClassName within a namespace.
    /// </summary>
    public static string BuildPartialClass(
        string ns,
        string className,
        ImmutableArray<SqlQueryGroup> groups,
        GeneratorConfig config,
        bool supportsNullable)
    {
        // Resolve the SqlStrings type name to use
        var stringsType = config.ExternalSqlStringsType
            ?? (config.UseSharedNamespace != null ? $"{config.UseSharedNamespace}.SqlStrings" : $"{config.SqlStringsNamespace}.SqlStrings");

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        if (supportsNullable)
        {
            sb.AppendLine(config.NullableEnabled ? "#nullable enable" : "#nullable disable");
        }

        if (config.UseSharedNamespace != null)
        {
            sb.AppendLine($"using {config.UseSharedNamespace};");
        }

        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    partial class {className}");
        sb.AppendLine("    {");

        foreach (var group in groups)
        {
            var hasDefault = group.ContentByProviderName.TryGetValue(FilePathParser.FallbackProviderName, out var defaultContent);
            sb.AppendLine($"        private static readonly {stringsType} Sql{group.QueryName} = new {stringsType}(");

            bool first = true;

            // Provider-specific — only emit when the file exists for that provider name
            foreach (var providerName in config.DistinctProviderNames)
            {
                if (group.ContentByProviderName.TryGetValue(providerName, out var content))
                {
                    if (!first) sb.AppendLine(",");
                    sb.Append($"            {providerName.ToLowerInvariant()}: @\"{content}\"");
                    first = false;
                }
            }

            if (hasDefault)
            {
                if (!first) sb.AppendLine(",");
                sb.Append($"            @default: @\"{defaultContent}\"");
            }

            sb.AppendLine(");");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    // ── Method Overloads ─────────────────────────────────────────────────

    public static string BuildOverloads(
        string ns,
        ITypeSymbol type,
        List<IMethodSymbol> methods,
        GeneratorConfig config,
        bool supportsNullable)
    {
        // Base visibility determines the maximum accessibility of the overloads
        var baseVisibility = (config.EmitSharedNamespace != null || config.ExternalSqlStringsType != null || config.UseSharedNamespace != null)
            ? "public"
            : "internal";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        if (supportsNullable)
        {
            sb.AppendLine(config.NullableEnabled ? "#nullable enable" : "#nullable disable");
        }

        sb.AppendLine("using SqlPartial.Abstractions;");
        if (config.UseSharedNamespace != null)
        {
            sb.AppendLine($"using {config.UseSharedNamespace};");
        }
        else if (config.EmitSharedNamespace != null)
        {
            sb.AppendLine($"using {config.EmitSharedNamespace};");
        }

        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");

        if (type.TypeKind == TypeKind.Interface)
        {
            sb.AppendLine($"    public static partial class {type.Name}SqlExtensions");
            sb.AppendLine("    {");

            foreach (var method in methods)
            {
                EmitOverload(sb, method, type, true, baseVisibility);
            }

            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine($"    partial {type.TypeKind.ToString().ToLower()} {type.Name}");
            sb.AppendLine("    {");

            foreach (var method in methods)
            {
                EmitOverload(sb, method, type, false, baseVisibility);
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitOverload(
        StringBuilder sb, IMethodSymbol method, ITypeSymbol type, bool isExtension, string baseVisibility)
    {
        var accessibility = method.DeclaredAccessibility.ToString().ToLower();

        // If ISqlString is internal, we cannot have a public/protected overload referencing it
        if (baseVisibility == "internal")
        {
            if (accessibility == "public" || accessibility == "protected" || accessibility == "protectedinternal")
            {
                accessibility = "internal";
            }
        }

        var isInterfaceExt = isExtension;
        var isOriginalExt = method.IsExtensionMethod;
        var isExt = isInterfaceExt || isOriginalExt;
        var staticKeyword = (method.IsStatic || isExt) ? "static " : "";
        var returnType = method.ReturnsVoid ? "void" : method.ReturnType.ToDisplayString();

        // Build generic version (TSql)
        sb.Append($"        {accessibility} {staticKeyword}{returnType} {method.Name}");

        // Handle generic parameters of the original method
        var methodGenerics = method.IsGenericMethod ? string.Join(", ", method.TypeParameters.Select(tp => tp.Name)) : "";
        if (method.IsGenericMethod) sb.Append("<" + methodGenerics + (methodGenerics == "" ? "" : ", ") + "TSql>");
        else sb.Append("<TSql>");

        sb.Append("(");
        bool isFirst = true;

        if (isExt)
        {
            var extensionType = isInterfaceExt ? type : method.Parameters[0].Type;
            sb.Append($"this {extensionType.ToDisplayString()} self");
            isFirst = false;
        }

        for (int i = 0; i < method.Parameters.Length; i++)
        {
            if (isOriginalExt && i == 0) continue; // Skip 'this' parameter for original extension methods

            if (!isFirst) sb.Append(", ");
            var param = method.Parameters[i];
            if (IsSqlAttribute(param))
            {
                sb.Append($"TSql {param.Name}");
            }
            else
            {
                sb.Append($"{param.Type.ToDisplayString()} {param.Name}");
            }

            if (param.HasExplicitDefaultValue)
            {
                sb.Append(" = ");
                sb.Append(FormatDefaultValue(param));
            }

            isFirst = false;
        }

        sb.AppendLine(") where TSql : struct, ISqlString");
        sb.AppendLine("        {");

        var providerAccess = isExt
            ? "self.SqlProviderName"
            : (method.IsStatic ? $"{type.Name}.SqlProviderName" : "this.SqlProviderName");

        var callPrefix = isInterfaceExt ? "self." : "";
        sb.Append($"            {(method.ReturnsVoid ? "" : "return ")}{callPrefix}{method.Name}");
        if (method.IsGenericMethod) sb.Append("<" + methodGenerics + ">");
        sb.Append("(");

        isFirst = true;
        for (int i = 0; i < method.Parameters.Length; i++)
        {
            if (!isFirst) sb.Append(", ");
            var param = method.Parameters[i];
            if (isOriginalExt && i == 0)
            {
                sb.Append("self");
            }
            else if (IsSqlAttribute(param))
            {
                sb.Append($"{param.Name}.Get({providerAccess})");
            }
            else
            {
                sb.Append(param.Name);
            }

            isFirst = false;
        }

        sb.AppendLine(");");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static bool IsSqlAttribute(IParameterSymbol param)
    {
        return param.GetAttributes().Any(a =>
            a.AttributeClass?.ToDisplayString() == "SqlPartial.Abstractions.SqlAttribute" ||
            a.AttributeClass?.Name == "SqlAttribute"); // Fallback for partial compilation
    }

    private static string FormatDefaultValue(IParameterSymbol param)
    {
        var value = param.ExplicitDefaultValue;
        if (value == null)
        {
            if (param.Type.IsReferenceType || (param.Type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T))
            {
                return "null";
            }
            return "default";
        }

        return SymbolDisplay.FormatPrimitive(value, quoteStrings: true, useHexadecimalNumbers: false);
    }
}
