using System.Text;
using TD.SqlPartial.Generator.Models;

namespace TD.SqlPartial.Generator.Core
{
    public static class SourceBuilder
    {
        public static string Build(SqlItem item)
        {
            var cleanedSql = SqlCleaner.Clean(item.Content);

            var sb = new StringBuilder();
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine("//     the code is regenerated.");
            sb.AppendLine("//");
            sb.AppendLine($"//     Source: {item.FilePath}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();

            if (item.NullableEnabled)
            {
                sb.AppendLine("#nullable enable");
                sb.AppendLine();
            }

            sb.AppendLine($"namespace {item.Namespace}");
            sb.AppendLine("{");

            var classModifier = string.IsNullOrWhiteSpace(item.ClassModifier) ? "" : $"{item.ClassModifier?.Trim()} ";
            sb.AppendLine($"    {classModifier}partial class {item.ClassName}");
            sb.AppendLine("    {");

            var constModifier = string.IsNullOrWhiteSpace(item.ConstModifier) ? "internal" : item.ConstModifier?.Trim();
            sb.AppendLine($"        {constModifier} const string {item.ConstName} = @\"{cleanedSql}\";");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
