using System.Collections.Immutable;
using System.Text;
using TD.SqlPartial.Generator.Models;

namespace TD.SqlPartial.Generator.Core
{
    internal static class SourceBuilder
    {
        // ── SqlStrings struct ────────────────────────────────────────────────

        /// <summary>
        /// Generates the SqlStrings struct definition.
        /// Called once per project when ExternalSqlStringsType is not set.
        /// </summary>
        public static string BuildSqlStringsStruct(GeneratorConfig config)
        {
            var sb = new StringBuilder();
            var ns = config.SqlStringsNamespace;
            var nullable = config.NullableEnabled ? "#nullable enable" : "#nullable disable";

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine(nullable);
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Holds SQL query strings for each configured DBMS provider.");
            sb.AppendLine("    /// Use <see cref=\"Get\"/> to retrieve the appropriate string at runtime.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public readonly struct SqlStrings");
            sb.AppendLine("    {");

            // AnsiSql property — always present
            sb.AppendLine("        /// <summary>ANSI SQL — shared fallback for all providers.</summary>");
            sb.AppendLine("        public string AnsiSql { get; init; }");
            sb.AppendLine();

            // One property per configured provider
            foreach (var provider in config.Providers)
            {
                sb.AppendLine($"        /// <summary>{provider.Name} specific SQL. Falls back to <see cref=\"AnsiSql\"/> when null.</summary>");
                sb.AppendLine($"        public string? {provider.Name} {{ get; init; }}");
                sb.AppendLine();
            }

            // Get(string providerName) method
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Returns the SQL string for the given provider name (from appsettings),");
            sb.AppendLine("        /// falling back to <see cref=\"AnsiSql\"/> when no specific string is configured.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public string Get(string providerName)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (providerName)");
            sb.AppendLine("            {");
            foreach (var provider in config.Providers)
            {
                sb.AppendLine($"                case \"{provider.Name}\":");
                sb.AppendLine($"                    return {provider.Name} ?? AnsiSql;");
            }
            sb.AppendLine("                default:");
            sb.AppendLine("                    return AnsiSql;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        // ── Partial class ────────────────────────────────────────────────────

        /// <summary>
        /// Generates one partial class file containing all SqlStrings properties
        /// for a single ClassName within a namespace.
        /// </summary>
        public static string BuildPartialClass(
            string ns,
            string className,
            ImmutableArray<SqlQueryGroup> groups,
            GeneratorConfig config)
        {
            // Resolve the SqlStrings type name to use
            var stringsType = config.ExternalSqlStringsType ?? $"{config.SqlStringsNamespace}.SqlStrings";

            var sb = new StringBuilder();
            var nullable = config.NullableEnabled ? "#nullable enable" : "#nullable disable";

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine(nullable);
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    partial class {className}");
            sb.AppendLine("    {");

            foreach (var group in groups)
            {
                sb.AppendLine($"        private static readonly {stringsType} Sql{group.QueryName} = new {stringsType}");
                sb.AppendLine("        {");

                // AnsiSql — always emitted
                var ansiContent = group.GetContent("an");
                sb.AppendLine($"            AnsiSql = @\"{ansiContent}\",");

                // Provider-specific — only emit when the file exists for that slug
                foreach (var provider in config.Providers)
                {
                    if (group.ContentBySlug.TryGetValue(provider.Slug, out var content))
                    {
                        sb.AppendLine($"            {provider.Name} = @\"{content}\",");
                    }
                }

                sb.AppendLine("        };");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
